normalizaNVIA<-function(devuelve){
  devuelve<-gsub("1 ","UNO ",devuelve)
  devuelve<-gsub("2 ","DOS ",devuelve)
  devuelve<-gsub("3 ","TRES ",devuelve)
  devuelve<-gsub("4 ","CUATRO ",devuelve)
  devuelve<-gsub("5 ","CINCO ",devuelve)
  devuelve<-gsub("6 ","SEIS ",devuelve)
  devuelve<-gsub("7 ","SIETE ",devuelve)
  devuelve<-gsub("8 ","OCHO ",devuelve)
  devuelve<-gsub("9 ","NUEVE ",devuelve)
  devuelve<-gsub("DR ","DOCTOR ",devuelve)
  devuelve<-gsub("DR\\.","DOCTOR ",devuelve)
  devuelve<-gsub("VTE","VICENTE",devuelve)
  devuelve<-gsub("FCO","FRANCISCO",devuelve)
  devuelve<-gsub("STA ","SANTA ",devuelve)
  devuelve<-gsub("FDEZ ","FERNANDEZ ",devuelve)
  devuelve<-gsub("Ð","Ñ",devuelve)
  devuelve<-gsub("¥","Ñ",devuelve)
  
  devuelve<-gsub(" I "," UNO ",devuelve)
  devuelve<-gsub(" II"," DOS ",devuelve)
  devuelve<-gsub(" III"," TRES ",devuelve)
  devuelve<-gsub(" IV"," CUATRO ",devuelve)
  devuelve<-gsub(" V "," CINCO ",devuelve)
  devuelve<-gsub(" VI "," SEIS ",devuelve)
  devuelve<-gsub(" VII"," SIETE ",devuelve)
  devuelve<-gsub(" VIII"," OCHO ",devuelve)
  devuelve<-gsub(" IX "," NUEVE ",devuelve)
  devuelve<-gsub(" X "," DIEZ ",devuelve)
  devuelve<-gsub(" XI"," ONCE ",devuelve)
  devuelve<-gsub(" XII"," DOCE ",devuelve)
  devuelve<-gsub(" XIII"," TRECE ",devuelve)
  devuelve<-gsub(" XIV "," CATORCE ",devuelve)
  devuelve<-gsub(" XV"," QUINCE ",devuelve)
  devuelve<-gsub(" XVI"," DIECISEIS ",devuelve)
  devuelve<-gsub(" XVII"," DIECISIETE ",devuelve)
  devuelve<-gsub(" XVIII"," DIECIOCHO ",devuelve)
  devuelve<-gsub(" IXX"," DIECINUEVE ",devuelve)
  devuelve<-gsub(" XX"," VEINTE ",devuelve)
  devuelve<-gsub(" XXI"," VEINTIUNO ",devuelve)
  
  devuelve<-gsub("999"," ",devuelve)
  devuelve<-gsub("9999"," ",devuelve)
  
  devuelve
}
